In [3]:
import pandas as pd

In [8]:
info = {
    "Name":["Zeyad","Aly","Wassam"],
    "CGPA":[9.5,9,8.5]
}

df = pd.DataFrame(info)
print(df)

     Name  CGPA
0   Zeyad   9.5
1     Aly   9.0
2  Wassam   8.5

In [9]:
df

     Name  CGPA
0   Zeyad   9.5
1     Aly   9.0
2  Wassam   8.5

In [28]:
#Series
s=pd.Series([1,2,3,4,"abc",5])
print(s)
print(type(s))
print(s.dtype)

#index
print(s[1])
print(s[0])

0      1
1      2
2      3
3      4
4    abc
5      5
dtype: object
<class 'pandas.core.series.Series'>
object
2
1

In [29]:
#lebeling
s=pd.Series([19, 6, 14, 16], index=(["Zeyad", "Aly", "Wassam", "Waqas",]))
print(s)

print(s.Zeyad)
print(s["Zeyad"])
print(s.Aly)

print(s[0])
print(s[1])

print(s.index)

Zeyad     19
Aly        6
Wassam    14
Waqas     16
dtype: int64
19
19
6
19
6
Index(['Zeyad', 'Aly', 'Wassam', 'Waqas'], dtype='object')

C:\Users\Irfan Ahmad\AppData\Local\Temp\ipykernel_27732\4132725642.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[0])
C:\Users\Irfan Ahmad\AppData\Local\Temp\ipykernel_27732\4132725642.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[1])

In [33]:
#vectorization
s1=pd.Series([1,2,3,4,5])
s2=pd.Series([10,20,30,40,50])

print(s1+s2)

#handle missing values with (NaN)
#mutable values, immutable size
s1[0]=100
print(s1)

changed=s1.drop(0)
print(s1)
print(changed)

0    11
1    22
2    33
3    44
4    55
dtype: int64
0    100
1      2
2      3
3      4
4      5
dtype: int64
0    100
1      2
2      3
3      4
4      5
dtype: int64
1    2
2    3
3    4
4    5
dtype: int64

In [45]:
#DataFrame
#(1) creating with the dictionary of list
info={
    "NAME":["Zeyad", "Aly", "Waqas", "Wassam"],
    "AGE":[19,5,16,14],
    "CGPA":[9.1,9.5,10,9.8]
}
df=pd.DataFrame(info)
print(df,type(df))

print(df.index)
print(df.columns)

     NAME  AGE  CGPA
0   Zeyad   19   9.1
1     Aly    5   9.5
2   Waqas   16  10.0
3  Wassam   14   9.8 <class 'pandas.core.frame.DataFrame'>
RangeIndex(start=0, stop=4, step=1)
Index(['NAME', 'AGE', 'CGPA'], dtype='object')

In [44]:
df

     NAME  AGE  CGPA
0   Zeyad   19   9.1
1     Aly    5   9.5
2   Waqas   16  10.0
3  Wassam   14   9.8

In [53]:
#(2) creating with list of list

df=pd.DataFrame([["zeyad",19,9.1],["aly",5,9],["wassam",14,9.5],["waqas",16,10]], columns=["NAME","AGE","CGPA"])
print(df)

     NAME  AGE  CGPA
0   zeyad   19   9.1
1     aly    5   9.0
2  wassam   14   9.5
3   waqas   16  10.0

In [54]:
df

     NAME  AGE  CGPA
0   zeyad   19   9.1
1     aly    5   9.0
2  wassam   14   9.5
3   waqas   16  10.0

In [58]:
#(3) creating with numpy arrays 
import numpy as np
np_arr=np.array([[1,2,3],[4,5,6]])
df=pd.DataFrame(np_arr, columns=["A","B","C"])
print(df)

   A  B  C
0  1  2  3
1  4  5  6

In [59]:
df

   A  B  C
0  1  2  3
1  4  5  6