In [3]:
import pandas as pd

In [8]:
info = {
    "Name":["Zeyad","Aly","Wassam"],
    "CGPA":[9.5,9,8.5]
}

df = pd.DataFrame(info)
print(df)

     Name  CGPA
0   Zeyad   9.5
1     Aly   9.0
2  Wassam   8.5

In [9]:
df

     Name  CGPA
0   Zeyad   9.5
1     Aly   9.0
2  Wassam   8.5

In [28]:
#Series
s=pd.Series([1,2,3,4,"abc",5])
print(s)
print(type(s))
print(s.dtype)

#index
print(s[1])
print(s[0])

0      1
1      2
2      3
3      4
4    abc
5      5
dtype: object
<class 'pandas.core.series.Series'>
object
2
1

In [29]:
#lebeling
s=pd.Series([19, 6, 14, 16], index=(["Zeyad", "Aly", "Wassam", "Waqas",]))
print(s)

print(s.Zeyad)
print(s["Zeyad"])
print(s.Aly)

print(s[0])
print(s[1])

print(s.index)

Zeyad     19
Aly        6
Wassam    14
Waqas     16
dtype: int64
19
19
6
19
6
Index(['Zeyad', 'Aly', 'Wassam', 'Waqas'], dtype='object')

C:\Users\Irfan Ahmad\AppData\Local\Temp\ipykernel_27732\4132725642.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[0])
C:\Users\Irfan Ahmad\AppData\Local\Temp\ipykernel_27732\4132725642.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[1])

In [33]:
#vectorization
s1=pd.Series([1,2,3,4,5])
s2=pd.Series([10,20,30,40,50])

print(s1+s2)

#handle missing values with (NaN)
#mutable values, immutable size
s1[0]=100
print(s1)

changed=s1.drop(0)
print(s1)
print(changed)

0    11
1    22
2    33
3    44
4    55
dtype: int64
0    100
1      2
2      3
3      4
4      5
dtype: int64
0    100
1      2
2      3
3      4
4      5
dtype: int64
1    2
2    3
3    4
4    5
dtype: int64

In [45]:
#DataFrame
#(1) creating with the dictionary of list
info={
    "NAME":["Zeyad", "Aly", "Waqas", "Wassam"],
    "AGE":[19,5,16,14],
    "CGPA":[9.1,9.5,10,9.8]
}
df=pd.DataFrame(info)
print(df,type(df))

print(df.index)
print(df.columns)

     NAME  AGE  CGPA
0   Zeyad   19   9.1
1     Aly    5   9.5
2   Waqas   16  10.0
3  Wassam   14   9.8 <class 'pandas.core.frame.DataFrame'>
RangeIndex(start=0, stop=4, step=1)
Index(['NAME', 'AGE', 'CGPA'], dtype='object')

In [44]:
df

     NAME  AGE  CGPA
0   Zeyad   19   9.1
1     Aly    5   9.5
2   Waqas   16  10.0
3  Wassam   14   9.8

In [53]:
#(2) creating with list of list

df=pd.DataFrame([["zeyad",19,9.1],["aly",5,9],["wassam",14,9.5],["waqas",16,10]], columns=["NAME","AGE","CGPA"])
print(df)

     NAME  AGE  CGPA
0   zeyad   19   9.1
1     aly    5   9.0
2  wassam   14   9.5
3   waqas   16  10.0

In [54]:
df

     NAME  AGE  CGPA
0   zeyad   19   9.1
1     aly    5   9.0
2  wassam   14   9.5
3   waqas   16  10.0

In [58]:
#(3) creating with numpy arrays 
import numpy as np
np_arr=np.array([[1,2,3],[4,5,6]])
df=pd.DataFrame(np_arr, columns=["A","B","C"])
print(df)

   A  B  C
0  1  2  3
1  4  5  6

In [59]:
df

   A  B  C
0  1  2  3
1  4  5  6

In [82]:
#work with csv file
df = pd.read_csv("employee_data.csv")
print(df,type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

In [102]:
#DataFrame methods

df.head()
df.head(2)
df.tail()
df.tail(4)
df.sample()
df.sample(5)
df.info()
df.shape
df.describe()
df.columns
df.nunique()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Department  10 non-null     object
 4   Salary      10 non-null     int64
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64

In [91]:
df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [81]:
#open json file
df=pd.read_json("employee_data.json")
print(df,type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

In [144]:
#work with AQI dataser
#by usinging DataFrame methods we are analysing the AQI 
import pandas as pd
df=pd.read_csv("globalAirQuality.csv")

# df
# df.head(10)
# df.shape
# df.describe()
# df.info()

#columns 
df[["country","city","aqi"]]

#rows
df.loc[0]
df.loc[0:2] #with loc ending index will be inclusive
df.iloc[0]
df.iloc[0:2] #with iloc ending index will be exclusive

#individual cell -row , col
df.loc[0,"aqi"]
df.loc[0,["city","aqi"]]
df.loc[0:2,["city","aqi"]]
df.loc[0:2,"city"]
#df.iloc[0:2,"city"] -> iloc required only numeric value thats it gives error here 
df.iloc[0:2,2]

df.loc[0:2,["country","city","latitude","longitude"]]
df.iloc[0:3,1:5]

df.at[0,"city"]
df.iat[0,2]

#checking view & copy
city=df["city"].copy() #use this to not change in original
city[0]="mumbai"
city #here will find out change in copy not in original

0          mumbai
1        New York
2        New York
3        New York
4        New York
           ...
17995      Zurich
17996      Zurich
17997      Zurich
17998      Zurich
17999      Zurich
Name: city, Length: 18000, dtype: object

In [145]:
#filtering data
df[df["aqi"] > 100]
df[(df["aqi"]>100) & (df["temperature"]>30) & (df["humidity"]>50)]
city_aqi_data=df[df["aqi"] > 100][["city","aqi"]]
city_aqi_data
city_aqi_data.iloc[0]
#city_aqi_data.loc[1] #give error because its not exist cuz it access with #lable
city_aqi_data.loc[3] #lable 3 is there in our city aqi data that why it give output
city_aqi_data.iloc[1] #its give output because its access with index vise no matter what is label

city    New York
aqi          158
Name: 3, dtype: object

In [146]:
#filtering data with query() method
df.query("aqi > 100 & temperature > 30") [["country","city","aqi"]]

# @ to reference python vars
aqi_val = 100
temp_val= 30
aqi_data=df.query("aqi > @aqi_val & temperature > @temp_val") [["country","city","aqi"]].copy()
aqi_data

      country      city  aqi
6          US  New York  155
7          US  New York  115
14         US  New York  121
17         US  New York  127
25         US  New York  113
...       ...       ...  ...
17947      CH    Zurich  107
17950      CH    Zurich  140
17975      CH    Zurich  111
17976      CH    Zurich  146
17991      CH    Zurich  104

[2384 rows x 3 columns]

In [147]:
df

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [148]:
#cleaning data - handling missing values

df=pd.read_csv("raw_data.csv")
df.isnull()
df.isna() #alies of isnull
df.isnull().sum()
df.dropna() #drop rows where NaN 
df.dropna(axis=1) #drop column where NaN 
df.fillna(0)

#filling column nall values with mean/avg values
age_mean=df["age"].mean()
cleaned_data=df.copy()
age_mean=cleaned_data["age"].mean()
cleaned_data["age"]=cleaned_data["age"].fillna(age_mean)
#cleaned_data

df.ffill()
df.bfill()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  34.0  Canada   Female  62000.0
3    3          Alex  34.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  51000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6    Ahmed Khan  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     USA     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  31.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [173]:
#cleaning data - handling dublicate values
df.duplicated() #row wise
df["country"].duplicated()
df[["country","name"]].duplicated()
df2=df.copy 
df.drop_duplicates(inplace=True) #we should not use inplace we should make copy of original data and then clean

In [177]:
#cleaning data - (handling data types and date-time)
df.dtypes
df2=df.copy()
df2=df2.fillna(0)
df2["age"]=df2["age"].astype("int64").copy()
df2.dtypes

df3=df.copy()
df3=df3.fillna(0)
df3["income"]=df3["income"].astype("int64").copy()
df3.dtypes

id           int64
name        object
age        float64
country     object
gender      object
income       int64
dtype: object

In [169]:
df2

    id          name  age country   gender   income
0    1      John Doe   29     USA     Male  55000.0
2    2    Jane Smith    0  Canada   Female  62000.0
3    3          Alex    0     USA  Unknown  47000.0
4    4  Maria Garcia   34   Spain   Female      0.0
5    5        Li Wei   27   China     Male  51000.0
6    6             0   45   India   Female  73000.0
7    7    Ahmed Khan   38       0     Male  68000.0
8    8    Rachel Lee   29     USA   Female  62000.0
9    9   Carlos Ruiz    0  Mexico     Male  45000.0
10  10   Emily Davis   31     USA        0  58000.0

In [178]:
df3

    id          name   age country   gender  income
0    1      John Doe  29.0     USA     Male   55000
2    2    Jane Smith   0.0  Canada   Female   62000
3    3          Alex   0.0     USA  Unknown   47000
4    4  Maria Garcia  34.0   Spain   Female       0
5    5        Li Wei  27.0   China     Male   51000
6    6             0  45.0   India   Female   73000
7    7    Ahmed Khan  38.0       0     Male   68000
8    8    Rachel Lee  29.0     USA   Female   62000
9    9   Carlos Ruiz   0.0  Mexico     Male   45000
10  10   Emily Davis  31.0     USA        0   58000

In [166]:
df #original

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [202]:
#data cleaning - (handle string)
df["gender"].str.lower()
df["gender"].str.upper()
df["gender"].str.capitalize()
df["name"].str.strip()
df["name"].str.split(" ") #before where we want to split we can fill the value in (" ")
df["country"].str.contains("india",case=False)

0     False
2     False
3     False
4     False
5     False
6      True
7       NaN
8     False
9     False
10    False
Name: country, dtype: object

In [190]:
#cleaning data - (to date-time)
aqi_data=pd.read_csv("globalAirQuality.csv")
aqi_data["timestamp"]=pd.to_datetime(aqi_data["timestamp"])
aqi_data["timestamp"].dtype

data_str=pd.Series([pd.to_datetime("10-10-2026")])
type(data_str.dtypes)

numpy.dtypes.DateTime64DType